---
- name: Ensure that Apache is installed Debian Style
  apt: name=apache2 state=present update_cache=yes
  when: ansible_os_family == "Debian"

- name: Ensure that Apache is installed RedHat Style
  yum: name=httpd state=present
  when: ansible_os_family == "RedHat"

- name: Start Apache Services (Debian)
  service: name=apache2 enabled=yes state=started
  when: ansible_os_family == "Debian"

- name: Start Apache Services (RedHat)
  service: name=httpd enabled=yes state=started
  when: ansible_os_family == "RedHat"

- name: Deploy apache configuration file (Debian)
  template: src=000-default.j2 dest=/etc/apache2/sites-enabled/000-default.conf
  notify:
    - Restart ApacheD
  when: ansible_os_family == "Debian"

- name: Deploy apache configuration file (Redhat) 
  template: src=httpd.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
    - Restart ApacheR
  when: ansible_os_family == "RedHat"

- name: Create content directory
  file: path={{ doc_root }}{{ doc_dir }} state=directory

- name: Copy Site Files 
  template: src=index.j2 dest={{ doc_root }}{{ doc_dir }}/index.html mode=u=rwX,g=rX,o=rX 
