---
- hosts: webservers
  become: yes 
  become_user: root
  vars: 
    http_port: 80
    doc_dir: /ansible
    doc_root: /var/www/html
    max_clients: 5
  vars_prompt:
    - name: username
      prompt: What is your name? What is your Quest? What is your fav color?

  tasks:
  - name: Ensure that Apache is installed Debian Style
    apt: name=apache2 state=present update_cache=yes
    when: ansible_os_family == "Debian"

  - name: Ensure that Apache is installed RedHat Style
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Services (Debian)
    service: name=apache2 enabled=yes state=started
    when: ansible_os_family == "Debian"

  - name: Start Apache Services (RedHat)
    service: name=httpd enabled=yes state=started
    when: ansible_os_family == "RedHat"

  - name: Deploy apache configuration file (Debian)
    template: src=templates/000-default.j2 dest=/etc/apache2/sites-enabled/000-default.conf
    notify:
      - Restart ApacheD
    when: ansible_os_family == "Debian"

  - name: Deploy apache configuration file (Redhat) 
    template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
      - Restart ApacheR
    when: ansible_os_family == "RedHat"

  - name: Create content directory
    file: path={{ doc_root }}{{ doc_dir }} state=directory

  - name: Copy Site Files 
    template: src=templates/index.j2 dest={{ doc_root }}{{ doc_dir }}/index.html mode=u=rwX,g=rX,o=rX 

  handlers:
    - name: Restart ApacheD
      service: name=apache2 state=restarted
    - name: Restart ApacheR
      service: name=httpd state=restarted

- hosts: dbservers
  become: yes 
  become_user: root

  tasks:
  - name: Ensure that mysql-server is installed
    apt: name=mysql-server state=present

  - name: Start mysql
    service: name=mysql enabled=yes state=started
  gather_facts: false
